import React,{useEffect,useState}from'react';import{createRoot}from'react-dom/client';import{supabase}from'./lib/supabaseClient';import'./styles.css';
type Profile={id:string;display_name:string|null;verification_status:string;is_banned:boolean;};type Conv={id:string;type:string;created_at:string};type Msg={id:string;conversation_id:string;sender_id:string;body:string|null;message_type:string;created_at:string;read_at:string|null};
function Auth({refresh}:{refresh:()=>void}){const[signup,setSignup]=useState(false),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[name,setName]=useState(''),[error,setError]=useState('');async function submit(e:React.FormEvent){e.preventDefault();setError('');if(signup){const r=await supabase.auth.signUp({email,password,options:{data:{display_name:name}}});if(r.error)setError(r.error.message);else setError('تم إنشاء الحساب. أكد الإيميل ثم سجل الدخول.')}else{const r=await supabase.auth.signInWithPassword({email,password});if(r.error)setError(r.error.message);else refresh();}}return <div className="auth"><form className="card" onSubmit={submit}><h1>ELshori7y</h1>{signup&&<input required placeholder="الاسم" value={name} onChange={e=>setName(e.target.value)}/>}<input required type="email" placeholder="الإيميل" value={email} onChange={e=>setEmail(e.target.value)}/><input required minLength={6} type="password" placeholder="كلمة السر" value={password} onChange={e=>setPassword(e.target.value)}/><button>{signup?'إنشاء حساب':'دخول'}</button>{error&&<p className="error">{error}</p>}<button type="button" className="ghost" onClick={()=>setSignup(!signup)}>{signup?'عندي حساب':'إنشاء حساب جديد'}</button></form></div>}
function App(){const[session,setSession]=useState<any>(null),[profile,setProfile]=useState<Profile|null>(null),[users,setUsers]=useState<Profile[]>([]),[convs,setConvs]=useState<Conv[]>([]),[active,setActive]=useState<string|null>(null),[messages,setMessages]=useState<Msg[]>([]),[query,setQuery]=useState(''),[text,setText]=useState(''),[loading,setLoading]=useState(true);const uid=session?.user?.id;
async function load(){const{data,error}=await supabase.auth.getSession();if(error){setSession(null);setProfile(null);setLoading(false);return}setSession(data.session);if(data.session){const{data:p}=await supabase.from('profiles').select('id,display_name,verification_status,is_banned').eq('id',data.session.user.id).single();setProfile(p);await loadConvs(data.session.user.id)}else setProfile(null);setLoading(false)}
async function loadConvs(id:string){const{data}=await supabase.from('conversation_participants').select('conversation_id').eq('user_id',id);const ids=(data??[]).map(x=>x.conversation_id);if(!ids.length){setConvs([]);return}const{data:c}=await supabase.from('conversations').select('id,type,created_at').in('id',ids).order('created_at',{ascending:false});setConvs(c??[]);}
async function openConv(id:string){setActive(id);const{data}=await supabase.from('messages').select('*').eq('conversation_id',id).order('created_at',{ascending:true});setMessages(data??[]);await supabase.rpc('mark_messages_read',{conversation_uuid:id});}
async function newChat(other:string){const{data,error}=await supabase.rpc('create_direct_conversation',{other_user_id:other});if(error){alert(error.message);return}await loadConvs(uid);await openConv(data);setQuery('');}
async function send(){if(!text.trim()||!active)return;const body=text.trim();setText('');const{error}=await supabase.from('messages').insert({conversation_id:active,sender_id:uid,body:body,message_type:'text'});if(error)alert(error.message);}
useEffect(()=>{load();const{data}=supabase.auth.onAuthStateChange(()=>load());return()=>data.subscription.unsubscribe()},[]);useEffect(()=>{if(!active)return;const ch=supabase.channel('messages-'+active).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages',filter:'conversation_id=eq.'+active},p=>setMessages(m=>m.some(x=>x.id===p.new.id)?m:[...m,p.new as Msg])).subscribe();return()=>{supabase.removeChannel(ch)}},[active]);useEffect(()=>{if(!uid)return;(async()=>{const{data}=await supabase.from('profiles').select('id,display_name,verification_status,is_banned').eq('verification_status','verified').eq('is_banned',false).neq('id',uid).limit(50);setUsers(data??[])})()},[uid]);
if(loading)return <div className="center">جاري التحميل...</div>;if(!session)return <Auth refresh={load}/>;if(!profile)return <div className="center">تعذر تحميل الحساب.</div>;if(profile.is_banned)return <div className="center">الحساب محظور.</div>;if(profile.verification_status!=='verified')return <div className="center card"><h2>الحساب قيد المراجعة</h2><p>بعد التحقق من الحساب هتقدر تستخدم المحادثات.</p><button onClick={()=>supabase.auth.signOut()}>خروج</button></div>;const filtered=users.filter(u=>(u.display_name??'').toLowerCase().includes(query.toLowerCase()));return <div><header><b>ELshori7y</b><button onClick={()=>supabase.auth.signOut()}>خروج</button></header><div className="layout"><aside><input placeholder="ابحث عن مستخدم" value={query} onChange={e=>setQuery(e.target.value)}/>{query&&filtered.map(u=><button className="user" key={u.id} onClick={()=>newChat(u.id)}>{u.display_name||'مستخدم'}</button>)}<h3>المحادثات</h3>{convs.map(c=><button className={'conv '+(active===c.id?'active':'')} key={c.id} onClick={()=>openConv(c.id)}>محادثة مباشرة</button>)}</aside><section className="chat"><div className="msgs">{active?messages.map(m=><div className={'msg '+(m.sender_id===uid?'mine':'')} key={m.id}>{m.body??''}<small>{new Date(m.created_at).toLocaleTimeString('ar-EG',{hour:'2-digit',minute:'2-digit'})}</small></div>):<div className="center">اختار محادثة أو ابحث عن مستخدم</div>}</div>{active&&<form className="composer" onSubmit={e=>{e.preventDefault();send()}}><input value={text} onChange={e=>setText(e.target.value)} placeholder="اكتب رسالة..."/><button>إرسال</button></form>}</section></div></div>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
