import React,{useCallback,useEffect,useState}from"react";
import{supabase}from"../lib/supabaseClient";
import StatCard from"../components/StatCard";
interface Stats{totalUsers:number;bannedUsers:number;messagesLast7Days:number;openReports:number;}
export default function Dashboard(){
 const[stats,setStats]=useState<Stats|null>(null);const[error,setError]=useState<string|null>(null);const[refreshing,setRefreshing]=useState(false);
 const load=useCallback(async()=>{setRefreshing(true);setError(null);try{const{data,error:e}=await supabase.rpc("admin_dashboard_stats");if(e)throw new Error(e.message);if(!data)throw new Error("لم ترجع قاعدة البيانات بيانات اللوحة");setStats({totalUsers:Number(data.total_users??0),bannedUsers:Number(data.banned_users??0),messagesLast7Days:Number(data.messages_last_7_days??0),openReports:Number(data.open_reports??0)});}catch(e:any){setError(e?.message||"تعذر تحميل بيانات لوحة التحكم");}finally{setRefreshing(false)}},[]);
 useEffect(()=>{void load();const id=window.setInterval(()=>{if(document.visibilityState==="visible")void load()},15000);return()=>window.clearInterval(id)},[load]);
 return <div className="admin-dashboard"><div className="page-heading"><div><span className="eyebrow">ELSHORI7Y CONTROL CENTER</span><h1>لوحة التحكم</h1><p>متابعة المنصة والمستخدمين والرسائل والبلاغات.</p></div><button className="primary-btn" onClick={()=>void load()} disabled={refreshing}>{refreshing?"جاري التحديث…":"تحديث البيانات"}</button></div>{error&&<div className="admin-error admin-error--box"><b>تعذر تحميل بيانات اللوحة</b><span>{error}</span><button onClick={()=>void load()}>إعادة المحاولة</button></div>}<div className="admin-dashboard__stats"><StatCard label="إجمالي المستخدمين" value={stats?.totalUsers??"—"}/><StatCard label="الحسابات المحظورة" value={stats?.bannedUsers??"—"}/><StatCard label="رسائل آخر 7 أيام" value={stats?.messagesLast7Days??"—"}/><StatCard label="بلاغات مفتوحة" value={stats?.openReports??"—"}/></div><div className="dashboard-panel"><div><span className="panel-kicker">SYSTEM STATUS</span><h2>كل حاجة تحت المراقبة</h2><p>التوثيق بيتم تلقائيًا من تأكيد البريد الإلكتروني. لوحة الإدارة مخصصة للإدارة والمراقبة والحظر والبلاغات.</p></div><div className="status-pill"><i/> ONLINE</div></div></div>}
